apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart
spec:
  concurrencyPolicy: Forbid
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: crontab-sample
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl:1.22.3
              command:
              - /bin/sh
              - -c
              - podIP=$(kubectl get pods -o jsonpath={.items[*].status.podIP}) && for ip in $podIP; do resp=$(curl $ip/ping/) > /dev/null 2>&1; echo " $ip - $resp"; done